name: Greenify
description: Live a greener life with Greenify!

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.png
    - assets/chat.png
    - assets/camera.png
    - assets/home.png
    - assets/cooking.png
    - assets/vehicle.png
    - assets/travel.png
    - assets/kim.png
    - assets/bigkimwalker.png
    - assets/backbutton.png
    - assets/signout.png
    - assets/background.png   
    - assets/foreground.png   
    - assets/app_icon.png   

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon.png"
